import { EXERCISE_LIBRARY as L } from '../src/data/exercises';
import { subMuscleOf } from '../src/lib/subMuscle';
import fs from 'fs';

const TAX = ['chest','back','shoulders','biceps','triceps','forearms','quads','hamstrings','glutes','calves','core'];
// Hand corrections where inference is wrong or a more precise region is known.
const OVERRIDES: Record<string,string> = {
  'barbell-reverse-wrist-curl': 'wrist_extensors',
  'db-reverse-wrist-curl': 'wrist_extensors',
  'atlas-stone-lift': 'lower_back',
  'sledgehammer-swing': 'obliques',
  'standing-power-throw': 'obliques',
  'dead-bug': 'lower_abs',
  'mountain-climber': 'lower_abs',
  'wall-sit': 'vastus',
  'sandbag-carry': 'obliques',
  'speed-bag': 'side_delt',
};

const tags: Record<string,string> = {};
for (const e of L) {
  if (!e.slug || !e.primaryMuscle || e.subMuscle) continue;      // only untagged, taxonomied
  if (!TAX.includes(e.primaryMuscle)) continue;
  const val = OVERRIDES[e.slug] ?? subMuscleOf({ name: e.name, primaryMuscle: e.primaryMuscle });
  if (val) tags[e.slug] = val;
}

const entries = Object.entries(tags).sort((a,b)=>a[0].localeCompare(b[0]));
const body = entries.map(([k,v]) => `  '${k}': '${v}',`).join('\n');
const out = `/**
 * Explicit sub-muscle tags for built-in exercises that ship without one in the
 * library literals. Generated by scripts/gen-submuscle-tags.ts (inference +
 * hand corrections), then committed as data so every exercise carries a pinned
 * sub-muscle rather than relying on runtime inference. Re-run the generator if
 * the library grows; hand corrections live in that script's OVERRIDES.
 */
export const SUB_MUSCLE_TAGS: Record<string, string> = {
${body}
};
`;
fs.writeFileSync('src/data/subMuscleTags.ts', out);
process.stdout.write(`wrote ${entries.length} tags\n`);
