#!/usr/bin/env node
/**
 * Pre-render the 100 achievement badge SVGs to PNG (base64) so the app can show
 * the real art with a plain <Image> — no runtime react-native-svg, which crashed
 * the Achievements screen natively on device.
 *
 * Reads the SVG strings from src/data/achievements.ts and writes
 * src/data/badgeImages.ts. Re-run whenever the badge art changes.
 *
 * Requires: npm install --no-save @resvg/resvg-js
 */
const fs = require('fs');
const path = require('path');
const { Resvg } = require('@resvg/resvg-js');

const SRC = path.join(__dirname, '..', 'src', 'data', 'achievements.ts');
const OUT = path.join(__dirname, '..', 'src', 'data', 'badgeImages.ts');
const SIZE = 96; // rendered px; badges display at ~48pt

const lines = fs.readFileSync(SRC, 'utf8').split(/\r?\n/);
const entries = [];
for (const line of lines) {
  const idM = line.match(/id:\s*(\d+),/);
  const svgM = line.match(/svg:\s*("(?:[^"\\]|\\.)*")/);
  if (idM && svgM) entries.push({ id: Number(idM[1]), svg: JSON.parse(svgM[1]) });
}
entries.sort((a, b) => a.id - b.id);
console.log('badges found:', entries.length);

let total = 0;
const rows = entries.map(({ id, svg }) => {
  const png = new Resvg(svg, { fitTo: { mode: 'width', value: SIZE }, background: 'rgba(0,0,0,0)' })
    .render()
    .asPng();
  const b64 = png.toString('base64');
  total += b64.length;
  return `  ${id}: 'data:image/png;base64,${b64}',`;
});

const out = `/**
 * Pre-rendered achievement badge art as base64 PNG data URIs.
 * GENERATED by scripts/render-badges.js — do not edit by hand. Re-run that
 * script if the badge SVGs in achievements.ts change.
 *
 * Rendered from the badge SVGs so the app shows the real art with a plain
 * <Image>, avoiding runtime react-native-svg (which crashed the Achievements
 * screen natively on device).
 */
export const BADGE_IMAGES: Record<number, string> = {
${rows.join('\n')}
};
`;

fs.writeFileSync(OUT, out, 'utf8');
console.log('wrote', OUT, '| approx base64 KB:', Math.round(total / 1024));
